/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n4.4-151-g5e61fce832-20210914"
#endif /* AVUTIL_FFVERSION_H */
